### ISSUE TITLE
justifyCenter not applied in the editor

### ISSUE THREAD

**Issue by confile** [Voog/wysihtml#199]
I read the docu here: https://github.com/Voog/wysihtml/wiki/Supported-Commands#justifyCenter

I set the button: 

```
<a data-wysihtml5-command="justifyCenter">align center</a>
```

I also set the parser rule and the css. 

Do I have to do "trigger via JavaScript" to make it work in the editor? I am not sure about that because bold does also work out of the box.

Did I miss something here?

**Comment by confile** [comment]
The problem is that it does not work with <textarea> tags. It only work well with divs.

**Comment by pulges** [comment]
The problem is probably that you did not add the stylesheet path in editor configuration when initiating editor
https://github.com/Voog/wysihtml/wiki/Getting-Started#5-use-a-set-of-css-classes-to-style-the-editors-content

var editor = new wysihtml5.Editor("wysihtml-textarea", { // id of textarea element
  toolbar:      "wysihtml-toolbar", // id of toolbar element
  parserRules:  wysihtml5ParserRules, // defined in parser rules set
  stylesheets:  "css/stylesheet.css"
});

justifyCenter adds a block wrapper element with wysiwyg-text-align-center class. The style of the classes has to be defined in css as in examples
https://github.com/Voog/wysihtml/blob/master/examples/css/stylesheet.css

As an alternative you can use the commands with style suffix "justifyCenterStyle" that do not do the class thing and add styles to elements style attribute inline.
