### ISSUE TITLE
option to create XHTML valid output - e.g. <br/> instead of <br>

### ISSUE THREAD

**Issue by jbrekle** [Voog/wysihtml#326]
Hi,

I love the project and am currently integrating it. Unfortunately I have to convert the output of the editor to our proprietary RTF format and therefore parse it as XML (in javascript). I encountered parse exceptions at unclosed `<br>` tags. I know that is valid HTML but I need it to be valid XML. There are several ways to fix it. E.g. I could string-replace them manually as a quick fix. Or use a different parser (which is hard as I use the browsers default parser). I think fixing this in wysihtml is quite reasonable because I don't know what else could be non-XML-compliant and others could have similar restraints. Maybe a config option is possible. 

Kind Regards,
Jonas

**Comment by pulges** [comment]
I think on wysihtml side doing this is quite difficult. The problem is that the html content is returned as browser handles it in javascript (element.innerHTML), but browsers tend not to return valid XHTML syntax with the slash at the end. Also the code might differ a lot between browsers and doctypes used. Thus the only way to do this is build various string parsers for outputs like (xhtml, html5, etc ...). Implementation would not benefit from browser at all and thus be exactly as difficult as you are doing on backend already.
